package com.example.travelmantics;

import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;

import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;

//recycler view accepts data from data source either an api or database
//here list of travel deals are sent to recycler view the data is sent to an adapter
//the adapter sends data to recycler view through viewHolder
//viewholder decribes a single data
//layout manager describes how data is shown in viewHolder
public class DealAdapter extends RecyclerView.Adapter<DealAdapter.DealViewHolder>{

    ArrayList<TravelDeal> deals;
    private FirebaseDatabase mFirebaseDatabase;
    private DatabaseReference mDatabaseReference;
    private ChildEventListener mChildEventListener;

    public DealAdapter(){
//        FirebaseUtil.openFbReference("traveldeals");
        mFirebaseDatabase = FirebaseUtil.mFirebaseDatabase;
        mDatabaseReference = FirebaseUtil.mDatabaseReference;

        this.deals = FirebaseUtil.mDeals;
        mChildEventListener = new ChildEventListener() {
            //first time activity loaded every item in database will triger this method
            @Override
            public void onChildAdded(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {
                //datasnapshot is immutable copy of data at the firebase databse location
                //they are passed to the methods in listeners
                //getValue method serializes the snapshot and adds it to travelDeal class
                TravelDeal td = dataSnapshot.getValue(TravelDeal.class);
                Log.d("Deal", td.getTitle());
                //set id of of deal to snapshot id generated by firebase
                td.setId(dataSnapshot.getKey());
                //add deal to list of deals
                deals.add(td);
                notifyItemInserted(deals.size() -1);
            }

            @Override
            public void onChildChanged(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onChildRemoved(@NonNull DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        };
        mDatabaseReference.addChildEventListener(mChildEventListener);
    }

    @NonNull
    @Override
    //called when recycler view needs a new viewholder
    public DealViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        Context context = parent.getContext();
        View itemView = LayoutInflater.from(context)
                .inflate(R.layout.rv_row, parent,false);
        return new DealViewHolder(itemView);
    }

    @Override
    //used to display the data
    public void onBindViewHolder(@NonNull DealViewHolder holder, int position) {
        TravelDeal deal = deals.get(position);
        holder.bind(deal);
    }

    @Override
    public int getItemCount() {
        return deals.size();
    }

    public class DealViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener{
        TextView tvTitle;
        TextView tvDescription;
        TextView tvPrice;
        public DealViewHolder(@NonNull View itemView) {
            super(itemView);
            tvTitle = (TextView) itemView.findViewById(R.id.tvTitle);
            tvDescription=(TextView) itemView.findViewById(R.id.tvDescription);
            tvPrice=(TextView) itemView.findViewById(R.id.tvPrice);
            itemView.setOnClickListener(this);

        }
        //bind data passsed to layout in row
        public void bind(TravelDeal deal){
            tvTitle.setText(deal.getTitle());
            tvPrice.setText(deal.getPrice());
            tvDescription.setText(deal.getDescription());
        }

        @Override
        public void onClick(View view) {
            //get position of item clicked
            int position = getAdapterPosition();
           Log.d("click", String.valueOf(position));
           TravelDeal selectedDeal = deals.get(position);
           Intent intent = new Intent(view.getContext(), DealActivity.class);
           intent.putExtra("Deal", selectedDeal);
           view.getContext().startActivity(intent);

        }
    }
}
